
set(ENABLED_GEMS
    Hitboy
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    AWSClientAuth
    AWSGameLift
    AWSMetrics
    Achievements
    AssetMemoryAnalyzer
    AssetValidation
    Atom_RPI
    Atom_Bootstrap
    Atom_AtomBridge
    AtomContent
    DccScriptingInterface
    Atom_Component_DebugCamera
    Atom_Feature_Common
    AtomFont
    AtomImGuiTools
    ImageProcessingAtom
    MaterialEditor
    AtomLyIntegration
    Atom_RHI
    Atom_RHI_DX12
    Atom_RHI_Metal
    Atom_RHI_Null
    Atom_RHI_Vulkan
    AtomShader
    AtomToolsFramework
    AtomTressFX
    AtomViewportDisplayIcons
    AtomViewportDisplayInfo
    BarrierInput
    Camera
    CertificateManager
    CommonFeaturesAtom
    CrashReporting
    CustomAssetExample
    DevTextures
    EMotionFX_Atom
    ExpressionEvaluation
    FastNoise
    GameStateSamples
    Gestures
    GradientSignal
    GraphCanvas
    GraphModel
    HttpRequestor
    ImguiAtom
    InAppPurchases
    LocalUser
    LyShineExamples
    Maestro
    MessagePopup
    Metastream
    Microphone
    MultiplayerCompression
    Blast
    NvCloth
    LmbrCentral
    PBSreferenceMaterials
    PhysXDebug
    PhysXSamples
    PrefabBuilder
    Presence
    PythonAssetBuilder
    QtForPython
    RADTelemetry
    ReferenceMaterials
    SceneLoggingExample
    SceneProcessing
    ScriptCanvas
    ScriptCanvasDeveloperGem
    ScriptCanvasTesting
    ScriptedEntityTweener
    SliceFavorites
    Sponza
    StartingPointCamera
    StartingPointMovement
    SurfaceData
    TestAssetBuilder
    TickBusOrderViewer
    Twitch
    UiBasics
    Vegetation
    VideoPlaybackFramework
    VirtualGamepad
    AudioEngineWwise
)
